version: "3"

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: jugaad
      MYSQL_USER: feli
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
      - ./setup/db/:/docker-entrypoint-initdb.d/

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

  php:
    image: felicityiiith/php
    ports:
      - "8080:80"
    volumes:
      - ./felicity-website:/var/www/html

  composer:
    image: composer
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - ./felicity-website:/app
    working_dir: /app
    command: 'composer install'

  gulp:
    image: node:8
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - ./felicity-website:/app
    working_dir: /app
    command: "bash -c 'yarn config set proxy ${HTTP_PROXY} && yarn global add gulp && yarn install && gulp watch'"

volumes:
  db:
