CREATE USER feli IDENTIFIED BY 'password';

CREATE DATABASE jugaad;
GRANT ALL ON jugaad.* TO feli;

CREATE DATABASE users;
GRANT ALL ON users.* TO feli;

CREATE DATABASE sap;
GRANT ALL ON sap.* TO feli;

CREATE DATABASE contest;
GRANT ALL ON contest.* TO feli;

FLUSH PRIVILEGES;
